install local babel-cli@6
fixes error caused by having babel@5 globally installed:

```
$ npm install

> virtex-dom@0.1.21 prepublish /.../virtex-dom
> rm -rf lib && babel src --out-dir lib

ReferenceError: [BABEL] src/canSelectText.js: Unknown option: /.../virtex-dom/.babelrc.presets
```